[fmt]
line_length = 120
number_underscore = 'thousands'
wrap_comments = false
quote_style = 'single'

[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = '0.8.25'
evm_version = "cancun" # Compile Curve LP interface
remappings = [
    '@delay-module=lib/delay-module/contracts/',
    '@roles-module=lib/roles-module/packages/evm/contracts/',
    '@gnosispay-kit=lib/account-kit/contracts/',
    '@balancer-v2=lib/balancer-v2-monorepo/pkg/',
    '@chainlink=lib/chainlink/contracts/src/v0.8/',
    '@oz=lib/openzeppelin-contracts/contracts/',
]
cbor_metadata = true

[rpc_endpoints]
gnosis = "https://rpc.gnosis.gateway.fm"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/demo"

[etherscan]
gnosis = { key = "${GNOSISSCAN_API_KEY}" }
